CREATE TABLE IF NOT EXISTS change_item_requests (
    change_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id INT NOT NULL,
    order_item_id INT NULL DEFAULT NULL,
    job_order_id INT NULL DEFAULT NULL,
    customer_id INT NULL DEFAULT NULL,
    sequence_no INT NOT NULL DEFAULT 1,
    source_channel VARCHAR(20) NOT NULL DEFAULT 'customer',
    created_by_user_id INT NULL DEFAULT NULL,
    created_by_role VARCHAR(20) NULL DEFAULT NULL,
    reason_code VARCHAR(64) NOT NULL,
    reason_label VARCHAR(255) NOT NULL,
    issue_description TEXT NOT NULL,
    staff_notes TEXT NULL,
    proof_path VARCHAR(512) NULL DEFAULT NULL,
    proof_original_name VARCHAR(255) NULL DEFAULT NULL,
    request_status VARCHAR(40) NOT NULL DEFAULT 'Requested',
    active_flag TINYINT NULL DEFAULT 1,
    rejection_reason TEXT NULL,
    reviewed_by_user_id INT NULL DEFAULT NULL,
    inventory_recorded_at DATETIME NULL DEFAULT NULL,
    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL DEFAULT NULL,
    approved_at DATETIME NULL DEFAULT NULL,
    rejected_at DATETIME NULL DEFAULT NULL,
    completed_at DATETIME NULL DEFAULT NULL,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(64) NULL DEFAULT NULL,
    verification_status VARCHAR(20) NULL DEFAULT NULL,
    PRIMARY KEY (change_item_id),
    UNIQUE KEY uq_order_active_change_item (order_id, active_flag),
    UNIQUE KEY uq_change_item_idempotency (idempotency_key),
    KEY idx_change_item_order (order_id, request_status),
    KEY idx_change_item_customer (customer_id, request_status),
    KEY idx_change_item_job (job_order_id),
    KEY idx_change_item_requested (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
