CREATE TABLE IF NOT EXISTS `payment_submissions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int DEFAULT NULL,
  `job_order_id` bigint DEFAULT NULL,
  `customer_id` int NOT NULL,
  `branch_id` int DEFAULT NULL,
  `receipt_file` varchar(500) NOT NULL,
  `receipt_storage_path` varchar(500) DEFAULT NULL,
  `receipt_url` varchar(700) DEFAULT NULL,
  `receipt_thumbnail` varchar(500) DEFAULT NULL,
  `receipt_original_name` varchar(255) DEFAULT NULL,
  `receipt_mime` varchar(100) DEFAULT NULL,
  `receipt_size` bigint unsigned NOT NULL DEFAULT 0,
  `receipt_sha256` char(64) DEFAULT NULL,
  `selected_payment_method` varchar(80) DEFAULT NULL,
  `submission_token` char(64) DEFAULT NULL,
  `expected_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `submitted_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `ocr_sender_name` varchar(190) DEFAULT NULL,
  `sender_name` varchar(190) DEFAULT NULL,
  `ocr_sender_mobile` varchar(40) DEFAULT NULL,
  `sender_mobile` varchar(40) DEFAULT NULL,
  `ocr_reference_number` varchar(190) DEFAULT NULL,
  `reference_number` varchar(190) DEFAULT NULL,
  `reference_normalized` varchar(190) DEFAULT NULL,
  `ocr_amount_sent` decimal(12,2) DEFAULT NULL,
  `amount_sent` decimal(12,2) DEFAULT NULL,
  `ocr_total_amount_sent` decimal(12,2) DEFAULT NULL,
  `total_amount_sent` decimal(12,2) DEFAULT NULL,
  `ocr_detected_payment_method` varchar(80) DEFAULT NULL,
  `detected_payment_method` varchar(80) DEFAULT NULL,
  `ocr_transaction_date` date DEFAULT NULL,
  `transaction_date` date DEFAULT NULL,
  `ocr_transaction_time` time DEFAULT NULL,
  `transaction_time` time DEFAULT NULL,
  `ocr_transaction_status` varchar(80) DEFAULT NULL,
  `transaction_status` varchar(80) DEFAULT NULL,
  `ocr_receiver_name` varchar(190) DEFAULT NULL,
  `receiver_name` varchar(190) DEFAULT NULL,
  `ocr_receiver_account` varchar(190) DEFAULT NULL,
  `receiver_account` varchar(190) DEFAULT NULL,
  `raw_ocr_text` mediumtext,
  `ocr_normalized_text` mediumtext,
  `overall_confidence` decimal(5,2) DEFAULT NULL,
  `sender_confidence` decimal(5,2) DEFAULT NULL,
  `sender_mobile_confidence` decimal(5,2) DEFAULT NULL,
  `reference_confidence` decimal(5,2) DEFAULT NULL,
  `amount_confidence` decimal(5,2) DEFAULT NULL,
  `total_amount_confidence` decimal(5,2) DEFAULT NULL,
  `method_confidence` decimal(5,2) DEFAULT NULL,
  `date_confidence` decimal(5,2) DEFAULT NULL,
  `receiver_confidence` decimal(5,2) DEFAULT NULL,
  `status_confidence` decimal(5,2) DEFAULT NULL,
  `ocr_status` varchar(30) NOT NULL DEFAULT 'Pending',
  `ocr_provider` varchar(50) DEFAULT NULL,
  `ocr_error` varchar(500) DEFAULT NULL,
  `ocr_attempts` smallint unsigned NOT NULL DEFAULT 0,
  `ocr_duration_ms` int unsigned DEFAULT NULL,
  `ocr_processed_at` datetime DEFAULT NULL,
  `amount_match_status` varchar(20) NOT NULL DEFAULT 'Unknown',
  `method_match_status` varchar(20) NOT NULL DEFAULT 'Unknown',
  `duplicate_submission_id` bigint unsigned DEFAULT NULL,
  `verification_status` varchar(40) NOT NULL DEFAULT 'Pending Review',
  `staff_notes` text,
  `rejection_reason` text,
  `corrected_by` int DEFAULT NULL,
  `corrected_at` datetime DEFAULT NULL,
  `verified_by` int DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_payment_submissions_order` (`order_id`, `created_at`),
  KEY `idx_payment_submissions_job` (`job_order_id`, `created_at`),
  KEY `idx_payment_submissions_customer` (`customer_id`, `created_at`),
  KEY `idx_payment_submissions_branch` (`branch_id`, `created_at`),
  KEY `idx_payment_submissions_queue` (`ocr_status`, `created_at`),
  KEY `idx_payment_submissions_review` (`verification_status`, `created_at`),
  KEY `idx_payment_submissions_reference` (`reference_normalized`),
  KEY `idx_payment_submissions_hash` (`receipt_sha256`),
  UNIQUE KEY `uq_payment_submissions_token` (`customer_id`, `submission_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Upgrade existing installations. These columns are OCR metadata only; the
-- original proof and core queue row remain reviewable if OCR is unavailable.
ALTER TABLE `payment_submissions`
  ADD COLUMN IF NOT EXISTS `ocr_normalized_text` mediumtext AFTER `raw_ocr_text`,
  ADD COLUMN IF NOT EXISTS `ocr_sender_mobile` varchar(40) DEFAULT NULL AFTER `sender_name`,
  ADD COLUMN IF NOT EXISTS `sender_mobile` varchar(40) DEFAULT NULL AFTER `ocr_sender_mobile`,
  ADD COLUMN IF NOT EXISTS `ocr_transaction_status` varchar(80) DEFAULT NULL AFTER `transaction_time`,
  ADD COLUMN IF NOT EXISTS `transaction_status` varchar(80) DEFAULT NULL AFTER `ocr_transaction_status`,
  ADD COLUMN IF NOT EXISTS `sender_mobile_confidence` decimal(5,2) DEFAULT NULL AFTER `sender_confidence`,
  ADD COLUMN IF NOT EXISTS `status_confidence` decimal(5,2) DEFAULT NULL AFTER `receiver_confidence`,
  ADD COLUMN IF NOT EXISTS `ocr_total_amount_sent` decimal(12,2) DEFAULT NULL AFTER `amount_sent`,
  ADD COLUMN IF NOT EXISTS `total_amount_sent` decimal(12,2) DEFAULT NULL AFTER `ocr_total_amount_sent`,
  ADD COLUMN IF NOT EXISTS `total_amount_confidence` decimal(5,2) DEFAULT NULL AFTER `amount_confidence`;
